
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dairo Montiel
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    /*Variables para vincular paneles y layout(cartas)*/
    private CardLayout cardLayout;
    private PanelMenu panelMenu;
    private PanelIMC panelIMC;
    private PanelTemperatura panelTemperatura;
    private PanelContactos panelContactos;
    
    public VentanaPrincipal() {
        initComponents();
    
    setResizable(false); //Impedir pantalla completa
    this.setSize(700,350); // ancho x alto en píxeles    
   
    
    //Inicializa el CardLayout.
    cardLayout = new CardLayout();
    
    // Layout principal
    panelContenedor.setLayout(cardLayout);
    
    /*Instancias de los paneles o "cartas".*/
    panelMenu = new PanelMenu(panelContenedor, cardLayout);
    panelIMC = new  PanelIMC(panelContenedor, cardLayout);
    panelTemperatura = new PanelTemperatura(panelContenedor, cardLayout);
    panelContactos = new  PanelContactos(panelContenedor, cardLayout);
       
    /*Añadir las cartas al contenedor principal */
    panelContenedor.add(panelMenu, "menu"); // "menu" es el identificador
    panelContenedor.add(panelIMC, "imc");   // "imc" es el identificador
    panelContenedor.add(panelTemperatura, "temperatura");
    panelContenedor.add(panelContactos, "contactos");
    
    //Configurar la ventana.
    this.setLocationRelativeTo(null); // Centra la ventana.
    
    /*Visualizar la primera carta(Menu) */
    cardLayout.show(panelContenedor, "menu");      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
